<?php

namespace App\Console\Commands;

use App\Models\Empleado;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

/**
 * Loads `empleados.orden_oficio`: the position each person has inside the
 * autogenerated attendance oficios (the order the Dirección's real Word
 * uses, which matches neither the Agenda order nor alphabetical order).
 *
 * The input is a JSON object { "<no_empleado>": <posición> }. It is derived
 * from the real oficio and stays in the git-ignored private storage — this
 * command never prints names or numbers, only aggregate counts.
 */
class ImportOrdenOficioCommand extends Command
{
    private const DEFAULT_FILE = 'imports/documentos-autogenerados/orden_oficio.json';

    /**
     * @var string
     */
    protected $signature = 'asistencia:importar-orden-oficio
        {archivo? : Ruta relativa al disco local (storage/app/private); por defecto '.self::DEFAULT_FILE.'}';

    /**
     * @var string
     */
    protected $description = 'Carga la posición de cada empleado dentro de los oficios de asistencia (orden_oficio).';

    public function handle(): int
    {
        $ruta = (string) ($this->argument('archivo') ?? self::DEFAULT_FILE);
        $disco = Storage::disk('local');

        if (! $disco->exists($ruta)) {
            $this->error("No se encontró el archivo {$ruta} en el disco local.");

            return self::FAILURE;
        }

        $orden = json_decode((string) $disco->get($ruta), true);

        if (! is_array($orden) || $orden === []) {
            $this->error('El archivo no contiene un objeto JSON {no_empleado: posición}.');

            return self::FAILURE;
        }

        $actualizados = 0;
        $sinEmpleado = 0;

        DB::transaction(function () use ($orden, &$actualizados, &$sinEmpleado) {
            foreach ($orden as $noEmpleado => $posicion) {
                if (! is_int($posicion) || $posicion < 1) {
                    continue;
                }

                $filas = Empleado::query()
                    ->where('no_empleado', (string) $noEmpleado)
                    ->update(['orden_oficio' => $posicion]);

                $filas > 0 ? $actualizados += $filas : $sinEmpleado++;
            }
        });

        $this->info("Empleados actualizados: {$actualizados}.");
        $this->line("Números del archivo sin empleado en la base: {$sinEmpleado}.");

        return self::SUCCESS;
    }
}
