<?php

namespace App\Http\Requests;

use App\Models\Estacion;
use App\Models\User;
use Closure;
use Database\Seeders\RoleSeeder;
use Illuminate\Contracts\Validation\ValidationRule;
use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;
use Illuminate\Validation\Rules\Password;

/**
 * Validates + authorizes creating a user account from the "Gestión de
 * usuarios" panel. Passwords are never auto-generated by the system — the
 * Administrador operating the panel must type one here, same "no default
 * password" principle as the existing console commands
 * (CreateZoneChiefCommand / CreateEstacionAccountCommand), just via a web
 * form instead of a CLI prompt.
 */
class StoreUserRequest extends FormRequest
{
    private const ESTACION_ROLE = 'Estación';

    public function authorize(): bool
    {
        return $this->user()?->can('create', User::class) ?? false;
    }

    /**
     * A blank <select> submits an empty string, not the absence of the
     * field — normalize it to null so the "nullable"/requiredIf rules
     * below see a real null rather than failing type checks.
     */
    protected function prepareForValidation(): void
    {
        if ($this->input('estacion_id') === '') {
            $this->merge(['estacion_id' => null]);
        }
    }

    /**
     * @return array<string, ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        return [
            'name' => ['required', 'string', 'max:255'],
            'email' => ['required', 'string', 'email', 'max:255', 'unique:users,email'],
            'role' => ['required', 'string', Rule::in(RoleSeeder::ROLES)],
            'estacion_id' => [
                Rule::requiredIf(fn () => $this->input('role') === self::ESTACION_ROLE),
                'nullable',
                'integer',
                'exists:estaciones,id',
                $this->estacionMustBeOperativaWhenRoleIsEstacion(),
            ],
            'password' => ['required', 'confirmed', Password::defaults()],
        ];
    }

    /**
     * An "Estación" account tied to the non-operational "Edificio Zonal
     * Este" wouldn't make sense — only Administrador may act on that one
     * (see RegistroDiarioPolicy). Only enforced when role === Estación;
     * an Administrador/Jefe de Zona account's estacion_id is ignored by
     * the service regardless of what's submitted here.
     */
    private function estacionMustBeOperativaWhenRoleIsEstacion(): Closure
    {
        return function (string $attribute, mixed $value, Closure $fail): void {
            if ($this->input('role') !== self::ESTACION_ROLE || $value === null) {
                return;
            }

            $isOperativa = Estacion::whereKey($value)->value('is_operativa');

            if (! $isOperativa) {
                $fail(__('La estación seleccionada no está operativa.'));
            }
        };
    }
}
