<?php

namespace App\Policies;

use App\Enums\TipoDocumentoAsistencia;
use App\Models\DocumentoAsistencia;
use App\Models\Estacion;
use App\Models\User;
use Carbon\CarbonInterface;
use Illuminate\Auth\Access\Response;

/**
 * Authorization for the autogenerated attendance oficios (Control de
 * Asistencia Diaria).
 *
 * - Station oficio: "Administrador" for any estación/fecha; an "Estación"
 *   account only for its own estación and only for today (same boundary
 *   as capturing — RegistroDiarioPolicy::captureForFecha()).
 * - Zone oficio: "Jefe de Zona" and "Administrador".
 * - Download: zone roles any oficio; an "Estación" account only its own
 *   station's oficios. Anything else is answered as 404, not 403, so
 *   nobody can probe which documents exist.
 *
 * Whether the data is complete (everything captured) is a business rule
 * checked by AsistenciaDocumentoService / the Form Requests, not here.
 */
class DocumentoAsistenciaPolicy
{
    private const ZONA_ROLES = ['Jefe de Zona', 'Administrador'];

    public function generarEstacion(User $user, Estacion $estacion, CarbonInterface $fecha): bool
    {
        if ($user->hasRole('Administrador')) {
            return true;
        }

        return $user->hasRole('Estación')
            && $user->estacion_id === $estacion->id
            && $fecha->isToday();
    }

    public function generarZona(User $user): bool
    {
        return $user->hasAnyRole(self::ZONA_ROLES);
    }

    public function descargar(User $user, DocumentoAsistencia $documento): Response
    {
        if ($user->hasAnyRole(self::ZONA_ROLES)) {
            return Response::allow();
        }

        if ($user->hasRole('Estación')
            && $documento->tipo === TipoDocumentoAsistencia::Estacion
            && $documento->estacion_id === $user->estacion_id) {
            return Response::allow();
        }

        return Response::denyAsNotFound();
    }
}
