<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Explicit row position inside the autogenerated attendance oficios
     * (Control de Asistencia Diaria). The order the Dirección expects does
     * not match orden_origen (Agenda) nor alphabetical order, so it is kept
     * as its own nullable column; NULLs sort last. Populated by
     * `php artisan asistencia:importar-orden-oficio`.
     */
    public function up(): void
    {
        Schema::table('empleados', function (Blueprint $table) {
            $table->unsignedSmallInteger('orden_oficio')->nullable()->index()->after('orden_origen');
        });
    }

    public function down(): void
    {
        Schema::table('empleados', function (Blueprint $table) {
            $table->dropColumn('orden_oficio');
        });
    }
};
