<?php

namespace App\Http\Controllers;

use App\Enums\TipoDocumentoAsistencia;
use App\Http\Requests\GenerarOficioEstacionRequest;
use App\Http\Requests\GenerarOficioZonaRequest;
use App\Models\DocumentoAsistencia;
use App\Services\AsistenciaDocumentoService;
use App\Services\Documentos\ConversionPdfException;
use App\Services\Documentos\MetadatosOficio;
use DomainException;
use Illuminate\Database\UniqueConstraintViolationException;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Str;
use Symfony\Component\HttpFoundation\StreamedResponse;

/**
 * Generation and download of the autogenerated attendance oficios (.docx +
 * .pdf). Thin-controller shape per .claude/rules/code-style.md.
 */
class AsistenciaDocumentoController extends Controller
{
    public function __construct(private readonly AsistenciaDocumentoService $service) {}

    public function storeEstacion(GenerarOficioEstacionRequest $request): RedirectResponse
    {
        $estacion = $request->estacionObjetivo();
        $fecha = $request->fechaObjetivo();
        $datos = $request->validated();

        try {
            $this->service->generarEstacion(
                $estacion,
                $fecha,
                new MetadatosOficio($datos['numero_oficio'], $datos['firmante_cargo'], $datos['firmante_nombre']),
                $request->user(),
            );
        } catch (DomainException|ConversionPdfException $e) {
            return back()->withInput()->withErrors(['oficio' => $e->getMessage()]);
        } catch (UniqueConstraintViolationException) {
            // Two requests raced for the same folio: report it like a normal validation error.
            return back()->withInput()->withErrors(['numero_oficio' => __('Ese No. de oficio ya fue asignado a otro documento.')]);
        }

        return redirect()
            ->route('asistencia.captura.index', $request->user()->hasRole('Administrador')
                ? ['estacion' => $estacion->id, 'fecha' => $fecha->toDateString()]
                : [])
            ->with('status', __('Oficio generado correctamente.'));
    }

    public function storeZona(GenerarOficioZonaRequest $request): RedirectResponse
    {
        $fecha = $request->fechaObjetivo();
        $datos = $request->validated();

        try {
            $this->service->generarZona($fecha, $datos['numero_oficio'], $datos['firmante'], $request->user());
        } catch (DomainException|ConversionPdfException $e) {
            return back()->withInput()->withErrors(['oficio' => $e->getMessage()]);
        } catch (UniqueConstraintViolationException) {
            // Two requests raced for the same folio: report it like a normal validation error.
            return back()->withInput()->withErrors(['numero_oficio' => __('Ese No. de oficio ya fue asignado a otro documento.')]);
        }

        return redirect()
            ->route('asistencia.zona.index', ['fecha' => $fecha->toDateString()])
            ->with('status', __('Oficio de zona generado correctamente.'));
    }

    public function download(Request $request, DocumentoAsistencia $documento, string $formato): StreamedResponse
    {
        $this->authorize('descargar', $documento);

        $ruta = $formato === 'pdf' ? $documento->pdf_path : $documento->docx_path;
        $disco = $this->service->disco();

        abort_unless($disco->exists($ruta), 404);

        activity('documento_asistencia')
            ->performedOn($documento)
            ->causedBy($request->user())
            ->withProperties(['formato' => $formato])
            ->log('descargado');

        return $disco->download($ruta, $this->nombreDeDescarga($documento, $formato));
    }

    /**
     * Human-friendly download name built only from server-side data.
     */
    private function nombreDeDescarga(DocumentoAsistencia $documento, string $formato): string
    {
        $alcance = $documento->tipo === TipoDocumentoAsistencia::Zona
            ? 'ZONA_ORIENTE'
            : Str::upper(Str::slug($documento->estacion->nombre, '_'));

        return sprintf('CONTROL_ASISTENCIA_%s_%s.%s', $alcance, $documento->fecha->format('Ymd'), $formato);
    }
}
