<?php

namespace App\Enums;

/**
 * Kind of autogenerated attendance oficio (Control de Asistencia Diaria):
 * one per station per day, and one zone-wide document per day.
 */
enum TipoDocumentoAsistencia: string
{
    case Estacion = 'estacion';
    case Zona = 'zona';

    public function label(): string
    {
        return match ($this) {
            self::Estacion => 'Oficio de estación',
            self::Zona => 'Oficio de zona',
        };
    }
}
